# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://bart-sokol.info/
gitlocation: https://github.com/bartsokol/bartsokol.github.io.git
gitbranch: master
title: Code and beyond
description: >
    Technology. By human, for human.

source: source/
blog: source/blog/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes
